### ISSUE TITLE
How to query the menus

### ISSUE THREAD

**Issue by richardrobberse** [stackbithq/gatsby-plugin-menus#7]
I've followed the readme, added a simple menus property to the frontmatter and now I'm at the point where I want to query the menus.
However, the query as listed in the readme is not valid and I can't find the 'menus' type at all.

Any ideas?

**Comment by richardrobberse** [comment]
Nevermind, the menus reside within sitePage\context.
It would've saved me a lot of time if it was noted in the docs ;)

**Comment by remotesynth** [comment]
Thanks for the feedback. The docs definitely need updating and I've added a task to do this.
